name: weather_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_config: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  retrofit: ^4.0.3
  dio: ^5.4.0
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  json_serializable: ^6.6.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  mocktail: ^1.0.1
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.5


flutter:
  uses-material-design: true
  generate: true